# Generated by Django 4.2.4 on 2023-09-01 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('details', models.TextField()),
                ('site_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.siteuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
