version: "3.4"

services:
  db:
    container_name: db_container
    image: postgres:15.4-alpine3.18
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deyal
    volumes:
      - dbdata:/var/lib/postgresql/data
  app:
    container_name: app_container
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9010:8000"
    depends_on:
      - db

volumes:
  dbdata:
