# Generated by Django 4.2.4 on 2023-09-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service'),
        ),
    ]
