# Generated by Django 4.2.4 on 2023-09-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0004_appointmentbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttime',
            name='details',
            field=models.CharField(help_text='Ex. Monday (9 PM to 11 PM)'),
        ),
    ]
